### ISSUE TITLE
Error while installing F-Droid, or other apk

### ISSUE THREAD

**Issue by MatzeMeile** [tigerbox-reverse-engineering/tigerbox#11]
Everything works till I want to Install the F-Droid.apk. Then I get following Message:

- exec '/system/bin/sh' failed: No such file or directory (2) -

If I create the directory /system/bin/ the error also is there.

**Comment by user0-07161** [comment]
I'm going to pick up here

**Comment by user0-07161** [comment]
Are you in recovery or in normal mode @MatzeMeile

**Comment by MatzeMeile** [comment]
The command adb devices shows recovery:

List of devices attached
0123456789ABCDEF	recovery

**Comment by user0-07161** [comment]
@MatzeMeile you have to follow the steps exactly

**Comment by user0-07161** [comment]
Your device is in recovery!

**Comment by user0-07161** [comment]
You have to mod it and then reboot

**Comment by user0-07161** [comment]
Follow the instructions exactly

**Comment by user0-07161** [comment]
Step for step

**Comment by MatzeMeile** [comment]
I think, i have a issue to switch from recovery mode to normal mode. The Tigerbox doesn't  switch in adb, mtp mode after i modify the build.prop. I am sure the file-transfer with the push command is working. I copy and fill in the lines for adb and debugging and change the line from charging to mtp,adb, but it isn't possible to get in the normal mode, to install apk.

**Comment by user0-07161** [comment]
ADb reboot?

**Comment by MatzeMeile** [comment]
Adb reboot restarts the box. Adb devices then shows empty lines for the list of devices. Other ADB commands shows, that there is no devices connected.

**Comment by user0-07161** [comment]
Send me your build.prop @MatzeMeile

**Comment by MatzeMeile** [comment]
The content of the build.prop:
[build.prop.txt](https://github.com/tigerbox-reverse-engineering/tigerbox/files/14329447/build.prop.txt)

**Comment by user0-07161** [comment]
Try upgrading the Box with the built in update option and repatch

**Comment by MatzeMeile** [comment]
Works! Thank you very much!

**Comment by user0-07161** [comment]
No problem of course!
